name: Build and deploy ASP.Net Core app to Azure Web App - contac-m-api

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

     # - name: Set up .NET Core
     #   uses: actions/setup-dotnet@v4
     #   with:
     #     dotnet-version: '8.x'

      - name: List environment variables
        run: printenv
        
      - name: List files in publish directory
        run: dir ${{env.GITHUB_WORKSPACE}}/myapp
       
         
